### PR TITLE
Add undo and redo

### PR DESCRIPTION
**Pull request by tranlehaiquan**
User can undo and redo (crt/cmd + z, crt/cmd + shift + z)

### CODE REVIEW

**Comment by lablnet** [comment]
> User can undo and redo (crt/cmd + z, crt/cmd + shift + z)

Thanks you so much will you able to add touch screen support or I merge this and open another issue?

**Comment by tranlehaiquan** [comment]
@lablnet Redo and undo will be the button in mobile?

**Comment by lablnet** [comment]
> @lablnet Redo and undo will be the button in mobile?

We can say gesture like three fingers swipe up for undo and down for redo

**Comment by tranlehaiquan** [comment]
@lablnet I kind tricky when use two fingers and three fingers in iPhone. Witch two fingers it is zoom in and out (and I can't disable that).

**Comment by lablnet** [comment]
> @lablnet I kind tricky when use two fingers and three fingers in iPhone. Witch two fingers it is zoom in and out (and I can't disable that).

Umm, unfortunately i am not iphone user so we can use similar  approach which will also work in iphones

**Comment by tranlehaiquan** [comment]
@lablnet I have added it ^^

**Review by lablnet — APPROVED** [review]
Thanks, you so much for your contribution. this PR is ready to merge.

**Pull request merged**
